### PR TITLE
fix(lib/api): make `Memory::new_from_existing(...)` compatible with wasmer 5.0

### LINKED ISSUE #5649: `Memory::new_from_existing(...)` is not compatible with wasmer 5.0
### Motivation

Suppose I want to get the base address of a memory created by wasmer to mark that memory as protected. To do that, I need something like this:

```toml
[package]
name = "wasmer-fail"
version = "0.1.0"
edition = "2024"

[dependencies]
region = "3"
# wasmer = { version = "5.0.6", default-features = false, features = ["singlepass", "wat"] }
# wasmer-vm = { version = "5.0.6", default-features = false }
wasmer = { version = "6.1.0-rc.2", default-features = false, features = ["singlepass", "wat"] }
windows-sys = { version = "0.59", features = ["Win32_System_Kernel", "Win32_System_Diagnostics_Debug"] }
```

```rust
use core::ptr;
use region::{Protection, protect};
use wasmer::{
    Instance, Memory, MemoryType, Module, Store, imports,
    sys::{
        NativeEngineExt,
        vm::{LinearMemory, init_traps}, //v6
    },
};
//use wasmer_vm::{LinearMemory, init_traps}; //v5
use windows_sys::Win32::{
    Foundation::EXCEPTION_ACCESS_VIOLATION,
    System::Diagnostics::Debug::{
        AddVectoredExceptionHandler, EXCEPTION_CONTINUE_EXECUTION, EXCEPTION_CONTINUE_SEARCH,
        EXCEPTION_POINTERS,
    },
};

static mut BASE: *mut u8 = ptr::null_mut();
static mut CURRENT_LENGTH: usize = 0;

unsafe extern "system" fn exception_handler(exception_info: *mut EXCEPTION_POINTERS) -> i32 {
    let record = unsafe { &*(*exception_info).ExceptionRecord };
    if record.ExceptionCode != EXCEPTION_ACCESS_VIOLATION {
        return EXCEPTION_CONTINUE_SEARCH;
    }

    let base = unsafe { BASE };
    let current_length = unsafe { CURRENT_LENGTH };

    let _ = unsafe { protect(base, current_length, Protection::READ_WRITE_EXECUTE) };

    EXCEPTION_CONTINUE_EXECUTION
}

fn main() {
    init_traps();
    unsafe { AddVectoredExceptionHandler(1, Some(exception_handler)) };

    let module_wat = r#"
(module
  (import "env" "memory" (memory 1))
  (func $init (export "init")
    (i32.store
      (i32.const 0x00)
      (i32.const 42)
    )
  )
)
    "#;
    let mut store = Store::default();
    if let Ok(module) = Module::new(&store, &module_wat) {
        let ty = MemoryType::new(1, Some(2), false);
        let tunables = store.engine().tunables();
        let style = tunables.memory_style(&ty);
        if let Ok(memory) = tunables.create_host_memory(&ty, &style) {
            let vm_memory_definition = memory.vmmemory();
            let vm_memory_definition_ref = unsafe { vm_memory_definition.as_ref() };

            let base = vm_memory_definition_ref.base;
            let current_length = vm_memory_definition_ref.current_length;

            unsafe {
                BASE = base;
                CURRENT_LENGTH = current_length;
            }

            if let Ok(_) = unsafe { protect(base, current_length, Protection::NONE) } {
                //let memory = Memory::new_from_existing(&mut store, memory); //v5
                let memory =
                    Memory::new_from_existing(&mut store, wasmer::vm::VMMemory::Sys(memory)); //v6???
                let import_object = imports! {
                    "env" => {
                        "memory" => memory,
                    }
                };
                if let Ok(instance) = Instance::new(&mut store, &module, &import_object) {
                    if let Ok(init) = instance.exports.get_function("init") {
                        let result = init.call(&mut store, &[]);
                        #[allow(unused_must_use)]
                        {
                            dbg!(result);
                        }
                    }
                }
            }
        }
    }
}
```

However, `Memory::new_from_existing()` no longer works as of version 6.0, since it accepts `wasmer::vm::VMMemory` (private type, also see #5648).

The current API looks like this:

```rust
// wasmer::Memory - public
#[derive(Debug, Clone, PartialEq, Eq, derive_more::From)]
#[cfg_attr(feature = "artifact-size", derive(loupe::MemoryUsage))]
pub struct Memory(pub(crate) BackendMemory);

impl Memory {
    pub fn new(store: &mut impl AsStoreMut, ty: MemoryType) -> Result<Self, MemoryError> {
        BackendMemory::new(store, ty).map(Self)
    }
}

// wasmer::entities::memory::inner::BackendMemory - private
#[cfg_attr(feature = "artifact-size", derive(loupe::MemoryUsage))]
#[derive(Debug, Clone, PartialEq, Eq, derive_more::From)]
pub(crate) enum BackendMemory {
    #[cfg(feature = "sys")]
    /// The implementation from the `sys` backend.
    Sys(crate::backend::sys::entities::memory::Memory),
}

// wasmer::backend::sys::entities::memory::Memory
#[derive(Debug, Clone)]
#[cfg_attr(feature = "artifact-size", derive(loupe::MemoryUsage))]
/// A WebAssembly `memory` in the `sys` runtime.
pub struct Memory {
    // wasmer::sys::vm::VMMemory, wasmer::sys::store::StoreHandle - public
    pub(crate) handle: StoreHandle<VMMemory>,
}

impl Memory {
    pub(crate) fn new(store: &mut impl AsStoreMut, ty: MemoryType) -> Result<Self, MemoryError> {
        let mut store = store.as_store_mut();
        let tunables = store.engine().tunables();
        let style = tunables.memory_style(&ty);
        let memory = tunables.create_host_memory(&ty, &style)?;

        Ok(Self {
            handle: StoreHandle::new(store.as_store_mut().objects_mut().as_sys_mut(), memory),
        })
    }
}
```

Technically I can create `wasmer::sys::vm::VMMemory` and `wasmer::sys::store::StoreHandle` manually, but then I can't create `wasmer::Memory` as before. 

### Proposed solution

Make `wasmer::vm::VMMemory` parameter voldemort type, for example as `impl Into<wasmer::vm::VMMemory>`. User does not have access to `wasmer::vm`, but can do `.into()` on `wasmer::sys::vm::VMMemory` (and on other backends).

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
# Description

Resolves #5649

### CODE REVIEW

File: lib/wasix/tests/runners.rs [hunk 1]
```diff
@@ -147,6 +147,7 @@ mod wcgi {
     use futures::{channel::mpsc::Sender, future::AbortHandle, SinkExt, StreamExt};
     use rand::Rng;
     use tokio::runtime::Handle;
+    use wasmer_package::utils::from_bytes;
```
Comment (StackOverflowExcept1on) [inline lib/wasix/tests/runners.rs:150]: RustRover can't sync the project due to errors here

**Comment by syrusakbary** [comment]
The PR looks good @StackOverflowExcept1on . It's having issues on the docs-rs build. If you can fix them, then we should be good to merge

**Comment by StackOverflowExcept1on** [comment]
@syrusakbary done

**Comment by StackOverflowExcept1on** [comment]
@syrusakbary done

**Review by syrusakbary — APPROVED** [review]
