### PR TITLE
Make the CLI respect the `--token` flag

### LINKED ISSUE #4028: Token/Registry Flag Handling Broken With --token + --registry flags
The recently introduced new token + registry flag handling in the CLI currently does not work when both 

`--token` and `--registry` are supplied as flags.

It seems like it will always try to get the token from the config for the given registry, even if the `--token` flag is supplied, resulting in a "not logged in" error.

@Michael-F-Bryan

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
The `WasmerEnv::token()` getter introduced in #4013 never checks the `--token` flag, so we were always using the token from a user's global config file.

Fixes #4028

### CODE REVIEW

File: lib/registry/src/wasmer_env.rs [hunk 1]
```diff
@@ -81,6 +81,12 @@ impl WasmerEnv {
 
     /// The API token for the active registry.
     pub fn token(&self) -> Option<String> {
+        if let Some(token) = &self.token {
```
Comment (theduke) [inline lib/registry/src/wasmer_env.rs:84]: Can we have a regression test for this?

Comment (Michael-F-Bryan) [reply lib/registry/src/wasmer_env.rs:84]: Done.

**Review by theduke — APPROVED** [review]
