### PR TITLE
Fix windows cache permission

### LINKED ISSUE #2454: Wasmer cli requires admin privilege on Windows due to cache
### Describe the bug

Trying to run a wasm module with the wasmer cli in a normal user level cli results in:
```sh
> wasmer exorbitant.wasm
error: failed to run `exorbitant.wasm`
│   1: module instantiation failed (engine: universal, compiler: cranelift)
╰─> 2: Access is denied. (os error 5)
```
Windows 10 using Wasmer 2.0 installed from the Windows Installer in the release.

### Steps to reproduce

From a user-privilege cli run: `wasmer <some wasm file>`

### Expected behavior

I expect the cli to be able to run and cache build results in user accessible folders. I do not expect to need admin privileges to run wasmer. 

### Additional context

Workarounds:
1. In a user-privilege cli disable the cache:
    ```sh
    wasmer run --disable-cache exorbitant.wasm
    ```

2. Run from a cmd with admin privledges:
    1. Press start and type cmd
    2. Right click on the "Command Prompt" option and choose "Run as administrator" (approve the UAC prompt as needed)
    3. Run wasmer in the admin prompt

Edit: The wasm file used: https://wapm.io/package/rajsite/exorbitant

### PR DESCRIPTION
**Pull request by chenyukang**
# Description
Fix issue #2454 , default `WASMER_CACHE_DIR` is not right for Windows.
Add more detailed messages for creating cache directory failure.

close #2454.

### CODE REVIEW

File: lib/cache/src/filesystem.rs [hunk 1]
```diff
@@ -63,8 +63,15 @@ impl FileSystemCache {
             }
         } else {
             // Create the directory and any parent directories if they don't yet exist.
-            create_dir_all(&path)?;
-            Ok(Self { path, ext: None })
+            let res = create_dir_all(&path);
+            if res.is_err() {
+                Err(io::Error::new(
+                    io::ErrorKind::Other,
```
Comment (Hywan) [inline lib/cache/src/filesystem.rs:69]: Why not using `io::ErrorKind::PermissionDenied` here? (cf https://doc.rust-lang.org/std/io/enum.ErrorKind.html)

**Review by Hywan — COMMENTED** [review]
Thank you for the PR! One last question before approving the PR.

File: lib/cache/src/filesystem.rs (hunk 1 above)
Comment (chenyukang) [reply lib/cache/src/filesystem.rs:69]: I was also hesitant to choose between `PermissionDenied` and `Other`, the reason I choose `Other` is considering we have some other reasons for failing to create a directory ....

`PermissionDenied` is also OK, since I mainly want to print a detailed message when the cache directory is failed to create.

File: scripts/windows-installer/wasmer.iss [hunk 2]
```diff
@@ -17,8 +17,6 @@ DisableWelcomePage=no
 [Registry]
 Root: HKCU; Subkey: "Environment"; ValueType:string; ValueName: "WASMER_DIR"; \
     ValueData: "{app}"; Flags: preservestringtype
-Root: HKCU; Subkey: "Environment"; ValueType:string; ValueName: "WASMER_CACHE_DIR"; \
-    ValueData: "{app}\cache"; Flags: preservestringtype
```
Comment (syrusakbary) [inline scripts/windows-installer/wasmer.iss:21]: If not provided, `WASMER_CACHE_DIR` will be `WASMER_DIR + "/cache"`

In this case, I think we should go to the value that worked before:

```suggestion
Root: HKCU; Subkey: "Environment"; ValueType:string; ValueName: "WASMER_CACHE_DIR"; \
    ValueData: "{%USERPROFILE}\.wasmer\cache"; Flags: preservestringtype
```

File: scripts/windows-installer/wasmer.iss [hunk 3]
```diff
@@ -28,9 +26,6 @@ Source: "..\..\package\LICENSE"; DestDir: "{app}"
 Source: "..\..\package\ATTRIBUTIONS"; DestDir: "{app}"
 Source: "wax.cmd"; DestDir: "{app}\bin"
 
-[Dirs]
-Name: "{app}\cache"
```
Comment (syrusakbary) [inline scripts/windows-installer/wasmer.iss:32]:
```suggestion
[Dirs]
Name: "{%USERPROFILE}\.wasmer"
```

File: scripts/windows-installer/wasmer.iss (hunk 2 above)
Comment (chenyukang) [reply scripts/windows-installer/wasmer.iss:21]: I think it's better not to set a register default value for it on Windows. We can keep the consistent usage style with Unix/Linux OS.

If users want to specify a cache directory, they can set an environment variable WASMER_CACHE_DIR, otherwise, env::temp_dir() will be used and it's safe for caching files.

/// Get the cache dir
pub fn get_cache_dir() -> PathBuf {
    match env::var("WASMER_CACHE_DIR") {
        Ok(dir) => {
            let mut path = PathBuf::from(dir);
            path.push(VERSION);
            path
        }
        Err(_) => {
            // We use a temporal directory for saving cache files
            let mut temp_dir = env::temp_dir();
            temp_dir.push("wasmer");
            temp_dir.push(VERSION);
            temp_dir
        }
    }
}
What do you think? @syrusakbary

File: lib/cache/src/filesystem.rs (hunk 1 above)
Comment (Hywan) [reply lib/cache/src/filesystem.rs:69]: Good to me.

**Review by syrusakbary — APPROVED** [review]
Looks great, merging!
