### PR TITLE
fix(runtime-core) Avoid crashing when missing host functions are allowed

### LINKED ISSUE #1118: allow_missing_functions doesn't work in release mode
In release mode, the `allow_missing_functions` option does not work as expected. Instantiation fails with a lot of `ImportNotFound` errors even with the field set to true.

Code to repro is [here](github.com/slipher/wasmer-bug). Steps:

```
git clone https://github.com/slipher/wasmer-bug
cd wasmer-bug
cargo build --release
target/release/sandbox cgame.wasm
```

In debug mode (`cargo build && target/debug/sandbox cgame.wasm`) it works as expected. I observed the same behavior of working only in debug mode on Windows and Linux machines.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #1118.
Address #1121.

This PR fixes 2 things:

* When droping the import backing, check that `vm::FuncCtx` isn't null before dropping it,
* Use an `always_trap` as a placeholder host function when a host function is missing.

### CODE REVIEW

File: lib/runtime-core/src/typed_func.rs [hunk 1]
```diff
@@ -258,11 +258,6 @@ where
             _phantom: PhantomData,
         }
     }
-
-    /// Get the underlying func pointer.
-    pub fn get_vm_func(&self) -> NonNull<vm::Func> {
-        self.func
-    }
```
Comment (MarkMcCaskey) [inline lib/runtime-core/src/typed_func.rs]: Is this a breaking change?

Comment (Hywan) [reply lib/runtime-core/src/typed_func.rs]: Nop. It was implemented for `Wasm` only, now it's implemented for `Wasm` and `Host`.
