### PR TITLE
Use trampolines for all libcalls in engine-universal and engine-dylib

### LINKED ISSUE #1722: probestack broken with engine-native and compiler-llvm
# Describe the bug

When building with --llvm and --native, `wast::llvm::spec::skip_stack_guard_page` fails with "out of bounds memory access" instead of the expected "call stack exhausted".

Let's take a quick look at one example:
```
(lldb) disassemble -s 0x7ffff77a0061
wasmer_nativexpTE17.so`wasmer_function__1:
    0x7ffff77a0061 <+1>:  pushq  %r15
    0x7ffff77a0063 <+3>:  pushq  %r14
    0x7ffff77a0065 <+5>:  pushq  %r13
    0x7ffff77a0067 <+7>:  pushq  %r12
    0x7ffff77a0069 <+9>:  pushq  %rbx
    0x7ffff77a006a <+10>: movl   $0x2098, %eax             ; imm = 0x2098 
    0x7ffff77a006f <+15>: callq  0x7ffff77a0020            ; symbol stub for: wasmer_probestack
    0x7ffff77a0074 <+20>: subq   %rax, %rsp
    0x7ffff77a0077 <+23>: movq   0x8(%rdi), %rbx
    0x7ffff77a007b <+27>: callq  0x7ffff77a0030            ; symbol stub for: wasmer_function__1
```

That wasmer_probestack stub is a PLT entry which looks like this:
```
(lldb) disassemble -s 0x7ffff77a0020
wasmer_nativexpTE17.so`wasmer_probestack:
    0x7ffff77a0020 <+0>:  jmpq   *0x9ffa(%rip)             ;  + 32
    0x7ffff77a0026 <+6>:  pushq  $0x1
    0x7ffff77a002b <+11>: jmp    0x7ffff77a0000
```
(you can ignore everything but the first instruction, __rust_probestack ends in a retq which will tail call return past this frame back to 0x7ffff77a006f)

That jmpq resolves to `0x000055555bde4148` which looks like bad code:
```
* thread #2, name = 'wast::llvm::spe', stop reason = instruction step into
    frame #0: 0x000055555bde4148
->  0x55555bde4148: jp     0x55555bde40df
    0x55555bde414a: movl   %ebx, 0x55(%rbx)
    0x55555bde414d: pushq  %rbp
    0x55555bde414e: addb   %al, (%rax)
```
but note that it is indeed the address of wasmer_probestack!
```
(lldb) p &wasmer_probestack
(void (**)()) $38 = 0x000055555bde4148
(lldb) p wasmer_probestack
(void (*)()) $39 = 0x000055555b89957a (compilers-95b529d63c259da9`__rust_probestack)
```
Somehow we jumped to the address of a global variable pointing to __rust_probestack instead of calling directly into __rust_probestack.

### PR DESCRIPTION
**Pull request by Amanieu**
In both of these engines, the compiled code may be loaded in memory far
from the Wasmer runtime which means that libcalls may not be reachable
through the normal relocation types. Instead a trampoline is needed to
allow reaching any address in the 64-bit address space.

In the case of engine-dylib, this is even worse since the symbols are
not exported by the executable without some special linker flags. The
solution here is to manually patch in the addresses at load time into
a data table of function pointers.

Fixes #1722

### CODE REVIEW

**Comment by Amanieu** [comment]
This is still incomplete: LLVM is bypassing the trampoline generation since it generates the object file directly.

**Comment by syrusakbary** [comment]
I think @ptitSeb will be the best one to review this

**Comment by Amanieu** [comment]
Ready for review

**Comment by syrusakbary** [comment]
This LGTM, @ptitSeb can you take a look to approve it or give feedback?

File: lib/compiler-cranelift/src/func_environ.rs [hunk 1]
```diff
@@ -1132,9 +1132,7 @@ impl<'module_environment> BaseFuncEnvironment for FuncEnvironment<'module_enviro
         Ok(func.import_function(ir::ExtFuncData {
             name,
             signature,
-            // We currently allocate all code segments independently, so nothing
-            // is colocated.
-            colocated: false,
+            colocated: true,
```
Comment (syrusakbary) [inline lib/compiler-cranelift/src/func_environ.rs:1135]: I might be missing some context on what colocated means. Why is this necessary?

Comment (Amanieu) [reply lib/compiler-cranelift/src/func_environ.rs:1135]: This is necessary to avoid text relocations. It means that all libcalls are reachable through normal call instructions (+/- 2G on x86, +/- 128M on aarch64) so it doesn't need to load the target from memory and do an indirect call. This is true since we generate trampolines that are near the compiled code.

The text relocations are due to the way Cranelift generates indirect calls: it places the target as a pointer in the .text section (since it puts everything in .text) and marks it with a relocation so the linker fills in the libcall address at load time.

**Review by ptitSeb — APPROVED** [review]
