### PR TITLE
fix(wasix): Remove redundant module hash generation in BinaryPackage

### LINKED ISSUE #4785: Resolve redundant BinaryPackage hashing
We currently have redundant hashing of the webc in BinaryPackages, which is no longer needed for webc v3s , since the hash is contained in the webc itself.<br><br>The redundant hashing step should be removed.

### PR DESCRIPTION
**Pull request by theduke**
The hash is already available, no need to re-compute.

Closes #4785

### CODE REVIEW

**Review by maminrayej — APPROVED** [review]

File: lib/wasix/src/bin_factory/binary_package.rs [hunk 1]
```diff
@@ -173,18 +173,25 @@ impl BinaryPackage {
...
         self.entrypoint_cmd
             .as_deref()
             .and_then(|name| self.get_command(name))
-            .map(|entry| entry.atom())
     }
 
+    /// Get the bytes for the entrypoint command.
+    pub fn entrypoint_bytes(&self) -> Option<&[u8]> {
+        self.get_entrypoint_cmd().map(|entry| entry.atom())
+    }
```
Comment (syrusakbary) [inline lib/wasix/src/bin_factory/binary_package.rs:186]: It seems `entrypoint_bytes` is only used in `bin_factor/exec.rs`. We should remove this function and refactor that code that is using it to be simpler:

```rust
if let Some(cmd) = binary.get_command(name).or(binary.get_entrypoint_cmd()) {
   ...
}
else {
}
```

Comment (theduke) [reply lib/wasix/src/bin_factory/binary_package.rs:186]: It's a public function, we shouldn't just remove those randomly.

Comment (syrusakbary) [reply lib/wasix/src/bin_factory/binary_package.rs:186]: We can mark it as deprecated if you prefer, and stop using it on our own code.

I don't think it adds any value (as we are the main users of the crate), but is your call if you prefer to deprecate it instead of deleting it

Comment (theduke) [reply lib/wasix/src/bin_factory/binary_package.rs:187]: Deprecated
