### PR TITLE
fix(engine-dylib): do not keep temp file and delete it automatically

### LINKED ISSUE #2501: Temp files are not removed in dylib engine
### Describe the bug

dylib creates tempfile to be able to "dlopen" later, but those files are not removed later. This could be an issue for a long running program which constantly (re)loads wasm files, occupying lots of unnecessary disk spaces.

### Steps to reproduce

Use dylib engine to load a wasm file, then check /tmp for temp files.

### Expected behavior

Temp file is deleted when not being used.

### Actual behavior

Temp file persists even program restarts.

### PR DESCRIPTION
**Pull request by bnjjj**
close #2501

# Description
This PR plan to fix the issue #2501 
I know the implementation using Drop trait is not the best way to implement it. Maybe I need more knowledge about engine lifecycle or adding a trait method to clean any artifacts we create when using an engine. Feel free to give me more details about how I could implement this in a better way.

### CODE REVIEW

File: lib/engine-dylib/src/artifact.rs [hunk 1]
```diff
@@ -58,6 +58,12 @@ pub struct DylibArtifact {
     frame_info_registration: Mutex<Option<GlobalFrameInfoRegistration>>,
 }
 
+impl Drop for DylibArtifact {
+    fn drop(&mut self) {
+        std::fs::remove_file(&self.dylib_path).expect("cannot delete the temporary artifact");
```
Comment (syrusakbary) [inline lib/engine-dylib/src/artifact.rs:63]: This will drop the file always, however there is only one scenario where we should do it.

`deserialize` (which creates a temporal file and then calls`deserialize_from_file_unchecked`) should delete the temporal file, however `deserialize_from_file` (which doesn't create a temporal file) should *not* delete the file (since it was provided by the user), we can provably have a new field specifying if the file is temporal or not and delete it on such case.

Comment (bnjjj) [reply lib/engine-dylib/src/artifact.rs:63]: Ok got it thank you, btw what's your policies regarding to error in this case ? Do you prefer to panic as I do here or just display a log ?

Comment (syrusakbary) [reply lib/engine-dylib/src/artifact.rs]: I think it might be better to gracefully dismiss the error in case the worst case scenario is reached, so logging seems like a better option than a panic.

Comment (bnjjj) [reply lib/engine-dylib/src/artifact.rs]: That's what I think too. Updated, thanks :)

Comment (syrusakbary) [reply lib/engine-dylib/src/artifact.rs]: That's great, will review now!

**Review by syrusakbary — APPROVED** [review]
Looks great! Merging soonish (as soon as bors test and merges)

**Comment by bnjjj** [comment]
Sorry I had to add a feature on dependency `tracing` for log in this crate

**Comment by syrusakbary** [comment]
No worries.

bors r+
