### PR TITLE
Prevent redundant merging of the filesystems

### LINKED ISSUE #5064: VFS: Regression in Union FS: Excessive copying of files
The new union FS implementation leads to excessive copying of files into the host file system, delaying startup significantly and causing lots of extra work.

To reproduce:

```
RUST_LOG=virtual_fs=trace,wasmer_wasix=trace wasmer run --registry wasmer.wtf  --net sha256:68c1f418474d98f0c4ca44d6754f144fe355525d1ba347dc52ab934cb98c5dad &| tee log.txt &

curl localhost:8080

❯ cat log.txt | grep 'Copying file into host filesystem' | wc -l
5846
```

This might also cause some kind of deadlocking or freezes, as seen in the app above.
The PHP code stalls and the request never returns.

### PR DESCRIPTION
**Pull request by maminrayej**
Another approach related to #5065.

Resolves #5064.

### CODE REVIEW

File: lib/wasix/src/runners/wasi.rs [hunk 1]
```diff
@@ -242,6 +242,7 @@ impl WasiRunner {
         let container_fs = if let Some(pkg) = pkg {
             builder.add_webc(pkg.clone());
             builder.set_module_hash(pkg.hash());
+            builder.include_package(pkg.id.clone());
```
Comment (theduke) [inline lib/wasix/src/runners/wasi.rs:245]: Isn't this too limited?

A BinaryPackage can consist of multiple dependencies providing file systems, do all of those need to be included here?

(I think this would require an extension to BinaryPackage, because the file system entries don't record their source package IDs, IIRC).

Comment (theduke) [reply lib/wasix/src/runners/wasi.rs:245]: Do we have a test that gets FS volumes from multiple dependencies?

**Comment by theduke** [comment]
@maminrayej please no force pushes here, I'll integrate into the edge branch.

File: lib/wasix/src/runners/wasi.rs (hunk 1 above)
Comment (maminrayej) [reply lib/wasix/src/runners/wasi.rs]: Yes, makes sense.

File: lib/wasix/src/state/env.rs [hunk 2]
```diff
@@ -1096,7 +1096,7 @@ impl WasiEnv {
 
         // We first need to copy any files in the package over to the
         // main file system
```
Comment (syrusakbary) [inline lib/wasix/src/state/env.rs:1098]: This comment is no longer relevant

**Review by syrusakbary — APPROVED** [review]
