### PR TITLE
Fix fd with append flag can't seek correctly

### LINKED ISSUE #5159: Cannot `fd_seek` with `fdflags::append`
### Describe the bug

If an fd was opened with `fdflags::append`, `fd_seek` with it does not work properly.

```sh
wasmer -vV; rustc -vV
wasmer 4.4.0 (8b97cfe 2024-10-18)
binary: wasmer-cli
commit-hash: 8b97cfe3992ae3c2f0002f9955fcb23057f666a9
commit-date: 2024-10-18
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift
c_api backend: 
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7
```

### Steps to reproduce

Compile the snippet with crate `wasi` v0.11, and run:

```
cargo build --target wasm32-wasip1
mkdir dir
wasmer run --mapdir /dir:dir target/wasm32-wasip1/debug/repro.wasm
```

```rust
fn main() {
    unsafe {
        let base_fd = 5;
        let rights = wasi::RIGHTS_FD_WRITE | wasi::RIGHTS_FD_TELL | wasi::RIGHTS_FD_SEEK;
        let fd = wasi::path_open(
            base_fd,
            0,
            "dir/file",
            wasi::OFLAGS_CREAT | wasi::OFLAGS_EXCL,
            rights,
            rights,
            0,
        )
        .unwrap();
        let fd_append = wasi::path_open(
            base_fd,
            0,
            "dir/file",
            wasi::OFLAGS_CREAT,
            rights,
            rights,
            wasi::FDFLAGS_APPEND,
        )
        .unwrap();

        assert_eq!(wasi::fd_seek(fd, 100, wasi::WHENCE_SET).unwrap(), 100);
        assert_eq!(
            wasi::fd_seek(fd_append, 100, wasi::WHENCE_SET).unwrap(),
            100
        );
    }
}
```

### Expected behavior

The snippet should run successfully. The two seeks should return the same offset.

### Actual behavior

Wasmer fails when running the snippet because the second `fd_seek` returns 0 as the offset.

### PR DESCRIPTION
**Pull request by yagehu**
This commit fixes an incompatible behavior (with other runtimes, and POSIX) when an fd that was opened with `fdflags::append` cannot seek to the right offset with `fd_seek`.  The append flag should not "lock" the offset at the end, as it's possible to seek to another offset and read from it.

This passes all the `wasi-fyi` tests.

fixes #5159

### CODE REVIEW

File: tests/wasi-fyi/fd_seek_append.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+            .create(true)
+            .append(true)
+            .open("/fyi/fs_seek_append.dir/file")
+            .unwrap();
+        let errno = fd_seek(
+            f.as_raw_fd(),
+            offset as i64,
+            WHENCE_SET,
+            &mut new_offset as *mut u64 as usize as i32,
+        );
```
Comment (syrusakbary) [inline tests/wasi-fyi/fd_seek_append.rs:27]: Could we have an example that triggers using only rust std (without importing any module from `wasi_snapshot_preview1`)?

That way we can have future-proof tests

Comment (yagehu) [reply tests/wasi-fyi/fd_seek_append.rs]: Absolutely. Fixed!

**Review by syrusakbary — COMMENTED** [review]
Great, thanks. Will wait for @maminrayej review
