### PR TITLE
Disable closures as host functions for now + docs + tests

### LINKED ISSUE #1811: Function::new_native support for closures with captured environments
### Describe the bug

`Function::new_native` seems to be playing fast and loose with closures.

`Cargo.toml`:
```toml
[dependencies]
anyhow = "1.0.34"
wasmer = "1.0.0-alpha5"
wasmer-compiler-cranelift = "1.0.0-alpha5"
wasmer-engine-jit = "1.0.0-alpha5"
```

For reference this (correctly) prints "42":
```rust
use anyhow::Result;
use wasmer::*;

fn main() -> Result<()> {
    let wat = r#"(module
        (import "console" "log" (func $log (param i32)))
        (func (export "main")
          i32.const 42
          call $log
        )
    )"#;
    let cranelift = Cranelift::default();
    let store = Store::new(&JIT::new(&cranelift).engine());
    let module = Module::new(&store, wat)?;
    let import_object = imports! {
        "console" => {
            "log" => Function::new_native(&store, |value: i32| {
                println!("{}", value);
            })
        }
    };
    let instance = Instance::new(&module, &import_object)?;
    let main: NativeFunc<(), ()> = instance
        .exports
        .get_native_function("main")?;
    main.call()?;
    Ok(())
}
```

This (incorrectly) crashes the program with a stack overflow:
```rust
use anyhow::Result;
use wasmer::*;
use std::sync::Arc;

fn main() -> Result<()> {
    let wat = r#"(module
        (import "console" "log" (func $log (param i32)))
        (func (export "main")
          i32.const 42
          call $log
        )
    )"#;
    let cranelift = Cranelift::default();
    let store = Store::new(&JIT::new(&cranelift).engine());
    let module = Module::new(&store, wat)?;
    let message = "message";
    let message_arc = Arc::new(message);
    let import_object = imports! {
        "console" => {
            "log" => Function::new_native(&store, move |value: i32| {
                println!("{}, {}", message_arc, value);
            })
        }
    };
    let instance = Instance::new(&module, &import_object)?;
    let main: NativeFunc<(), ()> = instance
        .exports
        .get_native_function("main")?;
    main.call()?;
    Ok(())
}
```

This (incorrectly) prints 0:
```rust
use anyhow::Result;
use wasmer::*;

fn main() -> Result<()> {
    let wat = r#"(module
        (import "console" "log" (func $log (param i32)))
        (func (export "main")
          i32.const 42
          call $log
        )
    )"#;
    let cranelift = Cranelift::default();
    let store = Store::new(&JIT::new(&cranelift).engine());
    let module = Module::new(&store, wat)?;
    let state = 1337;
    let import_object = imports! {
        "console" => {
            "log" => Function::new_native(&store, move |_: i32| {
                println!("{}", state);
            })
        }
    };
    let instance = Instance::new(&module, &import_object)?;
    let main: NativeFunc<(), ()> = instance
        .exports
        .get_native_function("main")?;
    main.call()?;
    Ok(())
}
```

### Additional context

Globally-installed things:
```
wasmer 1.0.0-alpha4
rustc 1.47.0 (18bf6b4f0 2020-10-07)
Windows 10 10.0.19042 N/A Build 19042
```

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
Resolves #1811 for now

Part of #1840 

# Review

- [x] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

File: lib/api/src/externals/function.rs [hunk 1]
```diff
@@ -130,6 +138,9 @@ impl Function {
         F: Fn(&Env, &[Val]) -> Result<Vec<Val>, RuntimeError> + 'static,
         Env: Sized + 'static,
     {
+        if std::mem::size_of::<F>() != 0 {
+            Self::closures_unsupported_panic();
+        }
```
Comment (syrusakbary) [inline lib/api/src/externals/function.rs:143]: I believe normal functions (not native), should still work. We should only disable native ones

Comment (MarkMcCaskey) [reply lib/api/src/externals/function.rs]: Oh, makes sense!  I've updated it to reflect that now

**Review by jubianchi — APPROVED** [review]

**Comment by Hywan** [comment]
It's going to break `wasmer-python`, and probably `wasmer-c-api` (didn't check for that one). Is it temporary?

**Comment by syrusakbary** [comment]
We don't support native closures with Wasmer... are they used in wasmer-python ?

**Comment by webmaster128** [comment]
We use this feature for a year of so without any issues. In our case, the `api` is copied into the closure: https://github.com/CosmWasm/cosmwasm/blob/upgrade-to-wasmer-reborn/packages/vm/src/instance.rs#L124-L130. For some reason this still compiles using wamer at 82fc0080ba6380a13dc2bdaea907cdf250f4d762. What am I missing here? Maybe I don't know what a "closure" is? Maybe copies are okay? Is the `move` making a difference?

**Comment by webmaster128** [comment]
In https://doc.rust-lang.org/book/ch13-01-closures.html#capturing-the-environment-with-closures there is a good explanation regarding naming and the different capture types. In Rust all anonymous functions are closures (no "lambda" as used in other languages). Then there are different types of environment capturing. And it turns out some of those captures (all captured data owned by the function) are still possible with this PR.

**Comment by Hywan** [comment]
> We don't support native closures with Wasmer... are they used in wasmer-python ?

Yes they are: https://github.com/wasmerio/wasmer-python/blob/99bd88d7f8a7cc4083625767d0cac77052456cb1/packages/api/src/externals/function.rs#L145-L193

It captures the `result_types` variable. Not that we can still store them in the environment 🤔.

**Comment by webmaster128** [comment]
I found why my code is not affected by this change. We use `Function::new_with_env`, but this PR is limited to `Function::new_native` and friends. Is this a missing check or should only "native" functions have the new restriction?

File: tests/compilers/native_functions.rs [hunk 2]
```diff
@@ -78,6 +78,90 @@ fn native_function_works_for_wasm() -> Result<()> {
...
+    let store = get_store(false);
+    let state = 3;
+    let env = 4;
+    Function::new_native_with_env(&store, env, move |_env: &i32, _: i32| {
+        println!("{}", state);
+    });
+}
+
+#[test]
+fn lambdas_with_no_env_work() -> Result<()> {
```
Comment (webmaster128) [inline tests/compilers/native_functions.rs:107]:
```suggestion
fn non_native_functions_and_closures_with_no_env_work() -> Result<()> {
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -21,6 +21,7 @@
 
 ### Fixed
 
+- [#1841](https://github.com/wasmerio/wasmer/pull/1841) We will now panic when attempting to use a function with a captured env as a host function. Previously this would silently do the wrong thing. See [#1840](https://github.com/wasmerio/wasmer/pull/1840) for info about Wasmer's support of closures as host functions.
```
Comment (webmaster128) [inline CHANGELOG.md:24]:
```suggestion
- [#1841](https://github.com/wasmerio/wasmer/pull/1841) We will now panic when attempting to use a native function with a captured env as a host function. Previously this would silently do the wrong thing. See [#1840](https://github.com/wasmerio/wasmer/pull/1840) for info about Wasmer's support of closures as host functions.
```

**Comment by syrusakbary** [comment]
> This means wasmerio/wasmer-python#420 was not needed.

Yeah, you are right @webmaster128

**Review by syrusakbary — APPROVED** [review]
