### PR TITLE
Fix/misc wasi fs issues

### LINKED ISSUE #434: __wasi_path_open incompatible with wasmtime
Thanks for the bug report!

### Describe the bug

When running the reproduction in wasmer, it gives an `EINVAL` error while opening a directory, but when running using wasmtime, it succeeds.

### Steps to reproduce

Unpack [rustc_binary.wasm](https://github.com/wasmerio/wasmer/files/3169038/rustc_binary.wasm.zip), then run the following commands:

```bash
$ echo 'fn main() { println!("Hello world!"); }' > example.rs
$ wasmer run rustc_binary.wasm --backend singlepass --dir . --dir $(rustc --print sysroot)  -- example.rs --sysroot $(rustc --print sysroot) -Zcodegen-backend=cranelift --target x86_64-unknown-linux # <-- change to the target triple of your host os
Couldn't read dir "/Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-wasi/lib": Os { code: 28, kind: Other, message: "Invalid argument" }
search_path files: []
Couldn't read dir "/Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib": Os { code: 28, kind: Other, message: "Invalid argument" }
search_path files: []
filesearch: FileSearch { sysroot: "/Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin", triple: "x86_64-apple-darwin", search_paths: [], tlib_path: SearchPath { kind: All, dir: "/Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib", files: [] }, kind: Crate }
filesearch: FileSearch { sysroot: "/Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin", triple: "wasm32-unknown-wasi", search_paths: [], tlib_path: SearchPath { kind: All, dir: "/Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-wasi/lib", files: [] }, kind: Crate }
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-apple-darwin` target may not be installed

$ wasmtime --dir . --dir $(rustc --print sysroot) ../../target/wasm32-unknown-wasi/release/rustc_binary.wasm -- example.rs --sysroot $(rustc --print sysroot) -Zcodegen-backend=cranelift --target x86_64-apple-darwin
[...] (lot of debug messages used to debug this problem)
[codegen mono items] start
error while processing main module ../../target/wasm32-unknown-wasi/release/rustc_binary.wasm: Instantiation error: Trap occurred while invoking start function: wasm trap at 0x2a4a9019b
# The trap above is expected.
```

### Expected behavior

Wasmer doesn't return `EINVAL` from `__wasi_path_open`, like wasmtime.

### Actual behavior

Wasmer returns `EINVAL` from `__wasi_path_open`.

### Additional context

```
~/Documents/wasmer $ git rev-parse HEAD
fa5402580f7f9f2d42d3345052c6781d8a5dce91
```

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
resolves #434

### CODE REVIEW

File: lib/wasi/src/syscalls/mod.rs [hunk 1]
```diff
@@ -1359,7 +1422,12 @@ pub fn path_open(
     }
 
     let mut cur_dir_inode = working_dir.inode;
-    let mut cumulative_path = std::path::PathBuf::from(".");
+    let mut cumulative_path = std::path::PathBuf::from(
+        state
+            .fs
+            .get_base_path_for_directory(working_dir.inode)
+            .expect("TODO"),
```
Comment (syrusakbary) [inline lib/wasi/src/syscalls/mod.rs]: Perhaps a better expect message will be better?

**Comment by syrusakbary** [comment]
It looks good. It might be good to add some kind of testing. But maybe best thing is merge and add integration tests after?
